"""Add op_finance tables (Manasety internal books)

Revision ID: 041c9042c5b6
Revises: b2c3d4e5f6a7
Create Date: 2026-05-04 10:35:44.816574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '041c9042c5b6'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('op_employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('employment_type', sa.String(length=20), nullable=False),
    sa.Column('monthly_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('joined_at', sa.Date(), nullable=False),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('op_employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_op_employees_full_name'), ['full_name'], unique=False)

    op.create_table('op_expense_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=120), nullable=False),
    sa.Column('item_name', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name', 'item_name', name='uq_op_category_item')
    )
    with op.batch_alter_table('op_expense_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_op_expense_categories_category_name'), ['category_name'], unique=False)

    op.create_table('op_fixed_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_name', sa.String(length=200), nullable=False),
    sa.Column('estimated_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('recurrence', sa.String(length=20), nullable=False),
    sa.Column('month_if_yearly', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('op_lenders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lender_name', sa.String(length=200), nullable=False),
    sa.Column('original_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('loan_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('op_lenders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_op_lenders_lender_name'), ['lender_name'], unique=False)

    op.create_table('op_finance_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('op_finance_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_op_finance_audit_logs_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_op_finance_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_op_finance_audit_logs_entity_type'), ['entity_type'], unique=False)

    op.create_table('op_incomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('income_date', sa.Date(), nullable=False),
    sa.Column('source_label', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('op_incomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_op_incomes_income_date'), ['income_date'], unique=False)

    op.create_table('op_loan_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lender_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['lender_id'], ['op_lenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('op_loan_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_op_loan_payments_lender_id'), ['lender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_op_loan_payments_payment_date'), ['payment_date'], unique=False)

    op.create_table('op_monthly_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['op_expense_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('op_monthly_expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_op_monthly_expenses_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_op_monthly_expenses_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_op_monthly_expenses_year'), ['year'], unique=False)

    op.create_table('op_payroll_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['op_employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('op_payroll_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_op_payroll_payments_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_op_payroll_payments_payment_date'), ['payment_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('op_payroll_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_op_payroll_payments_payment_date'))
        batch_op.drop_index(batch_op.f('ix_op_payroll_payments_employee_id'))

    op.drop_table('op_payroll_payments')
    with op.batch_alter_table('op_monthly_expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_op_monthly_expenses_year'))
        batch_op.drop_index(batch_op.f('ix_op_monthly_expenses_month'))
        batch_op.drop_index(batch_op.f('ix_op_monthly_expenses_category_id'))

    op.drop_table('op_monthly_expenses')
    with op.batch_alter_table('op_loan_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_op_loan_payments_payment_date'))
        batch_op.drop_index(batch_op.f('ix_op_loan_payments_lender_id'))

    op.drop_table('op_loan_payments')
    with op.batch_alter_table('op_incomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_op_incomes_income_date'))

    op.drop_table('op_incomes')
    with op.batch_alter_table('op_finance_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_op_finance_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_op_finance_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_op_finance_audit_logs_action_type'))

    op.drop_table('op_finance_audit_logs')
    with op.batch_alter_table('op_lenders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_op_lenders_lender_name'))

    op.drop_table('op_lenders')
    op.drop_table('op_fixed_expenses')
    with op.batch_alter_table('op_expense_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_op_expense_categories_category_name'))

    op.drop_table('op_expense_categories')
    with op.batch_alter_table('op_employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_op_employees_full_name'))

    op.drop_table('op_employees')
    # ### end Alembic commands ###
