"""Add admin RBAC: roles + permissions tables, role_id FK on admin_users

Revision ID: 15c82f187091
Revises: 041c9042c5b6
Create Date: 2026-05-05 08:54:04.634909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15c82f187091'
down_revision = '041c9042c5b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('name_ar', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_roles_name'), ['name'], unique=True)

    op.create_table('admin_role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=60), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['admin_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'module', 'action', name='uq_admin_role_perm')
    )
    with op.batch_alter_table('admin_role_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_role_permissions_role_id'), ['role_id'], unique=False)

    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_admin_users_role_id'), ['role_id'], unique=False)
        batch_op.create_foreign_key(None, 'admin_roles', ['role_id'], ['id'], ondelete='SET NULL')

    # ── Seed: Super Admin (system role, all permissions) + 2 default custom roles ──
    # Use raw SQL via op.execute so this works regardless of model state.
    bind = op.get_bind()
    now = sa.func.now()

    # Re-import the catalogue here so the migration is self-contained
    PERMISSION_CATALOGUE = [
        {'group_ar': 'إدارة المكاتب', 'modules': [
            {'key': 'tenants',  'actions': ['view','add','edit','delete']},
            {'key': 'plans',    'actions': ['view','add','edit','delete']},
            {'key': 'features', 'actions': ['view','edit']},
        ]},
        {'group_ar': 'المالية (الاشتراكات)', 'modules': [
            {'key': 'billing', 'actions': ['view','add','edit','delete']},
        ]},
        {'group_ar': 'الإدارة المالية الداخلية', 'modules': [
            {'key': 'finance_dashboard', 'actions': ['view']},
            {'key': 'finance_employees', 'actions': ['view','add','edit','delete']},
            {'key': 'finance_payroll',   'actions': ['view','add','delete']},
            {'key': 'finance_lenders',   'actions': ['view','add','edit','delete']},
            {'key': 'finance_expenses',  'actions': ['view','add','edit','delete']},
            {'key': 'finance_income',    'actions': ['view','add','delete']},
        ]},
        {'group_ar': 'العمليات', 'modules': [
            {'key': 'notifications', 'actions': ['view','send']},
            {'key': 'audit_log',     'actions': ['view']},
        ]},
        {'group_ar': 'النظام', 'modules': [
            {'key': 'settings',     'actions': ['view','edit']},
            {'key': 'admin_users',  'actions': ['view','add','edit','delete']},
            {'key': 'admin_roles',  'actions': ['view','add','edit','delete']},
        ]},
    ]

    all_pairs = [(m['key'], a) for g in PERMISSION_CATALOGUE for m in g['modules'] for a in m['actions']]

    def insert_role(name, name_ar, description, is_system):
        return bind.execute(sa.text("""
            INSERT INTO admin_roles (name, name_ar, description, is_system, created_at, updated_at)
            VALUES (:name, :name_ar, :description, :is_system, NOW(), NOW())
            RETURNING id
        """), {'name': name, 'name_ar': name_ar, 'description': description, 'is_system': is_system}).scalar()

    def grant(role_id, pairs):
        for module, action in pairs:
            bind.execute(sa.text("""
                INSERT INTO admin_role_permissions (role_id, module, action)
                VALUES (:role_id, :module, :action)
            """), {'role_id': role_id, 'module': module, 'action': action})

    # 1. Super Admin (system) — gets every pair, but checks short-circuit anyway
    super_id = insert_role('super_admin', 'Super Admin',
                           'دور النظام الافتراضي — صلاحيات كاملة، لا يمكن حذفه أو تعديل صلاحياته.',
                           is_system=True)
    grant(super_id, all_pairs)

    # 2. محاسب (Accountant) — finance + read on tenants/plans/audit
    accountant_pairs = [
        ('billing', a) for a in ['view', 'add', 'edit', 'delete']
    ] + [
        (m['key'], a)
        for g in PERMISSION_CATALOGUE if g['group_ar'] == 'الإدارة المالية الداخلية'
        for m in g['modules'] for a in m['actions']
    ] + [
        ('tenants', 'view'), ('plans', 'view'),
        ('audit_log', 'view'), ('settings', 'view'),
    ]
    acc_id = insert_role('accountant', 'محاسب',
                         'يدير الفواتير والإدارة المالية الداخلية + قراءة بيانات المكاتب.',
                         is_system=False)
    grant(acc_id, accountant_pairs)

    # 3. مشرف مكاتب (Office Supervisor) — tenants/plans/features write + read on billing/audit
    supervisor_pairs = [
        ('tenants', a)  for a in ['view','add','edit','delete']
    ] + [
        ('plans',   a)  for a in ['view','add','edit','delete']
    ] + [
        ('features', a) for a in ['view','edit']
    ] + [
        ('billing', 'view'), ('audit_log', 'view'), ('notifications', 'view'),
        ('settings', 'view'),
    ]
    sup_id = insert_role('office_supervisor', 'مشرف مكاتب',
                         'يدير المكاتب والخطط والميزات + قراءة الفواتير وسجل العمليات.',
                         is_system=False)
    grant(sup_id, supervisor_pairs)

    # 4. Backfill: link any AdminUser whose legacy `role` column is 'super_admin'
    # to the Super Admin role row, so existing logins keep working post-migration.
    bind.execute(sa.text("""
        UPDATE admin_users SET role_id = :rid WHERE role = 'super_admin'
    """), {'rid': super_id})

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_admin_users_role_id'))
        batch_op.drop_column('role_id')

    with op.batch_alter_table('admin_role_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_role_permissions_role_id'))

    op.drop_table('admin_role_permissions')
    with op.batch_alter_table('admin_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_roles_name'))

    op.drop_table('admin_roles')
    # ### end Alembic commands ###
