"""Add scope to admin permissions + created_by_admin_id on scoped entities

Revision ID: a0e0fcc48c4b
Revises: 15c82f187091
Create Date: 2026-05-06 10:22:22.516416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e0fcc48c4b'
down_revision = '15c82f187091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add `scope` with server_default='all' so existing rows are backfilled
    # without a separate UPDATE step. New rows can override via the model
    # default ('all') or by explicit assignment.
    with op.batch_alter_table('admin_role_permissions', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('scope', sa.String(length=10), nullable=False, server_default='all')
        )

    with op.batch_alter_table('op_employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_admin_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_op_employees_created_by_admin_id'), ['created_by_admin_id'], unique=False)
        batch_op.create_foreign_key(None, 'admin_users', ['created_by_admin_id'], ['id'])

    with op.batch_alter_table('op_expense_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_admin_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_op_expense_categories_created_by_admin_id'), ['created_by_admin_id'], unique=False)
        batch_op.create_foreign_key(None, 'admin_users', ['created_by_admin_id'], ['id'])

    with op.batch_alter_table('op_fixed_expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_admin_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_op_fixed_expenses_created_by_admin_id'), ['created_by_admin_id'], unique=False)
        batch_op.create_foreign_key(None, 'admin_users', ['created_by_admin_id'], ['id'])

    with op.batch_alter_table('op_lenders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_admin_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_op_lenders_created_by_admin_id'), ['created_by_admin_id'], unique=False)
        batch_op.create_foreign_key(None, 'admin_users', ['created_by_admin_id'], ['id'])

    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_admin_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_subscription_plans_created_by_admin_id'), ['created_by_admin_id'], unique=False)
        batch_op.create_foreign_key(None, 'admin_users', ['created_by_admin_id'], ['id'])

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_admin_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tenants_created_by_admin_id'), ['created_by_admin_id'], unique=False)
        batch_op.create_foreign_key(None, 'admin_users', ['created_by_admin_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tenants_created_by_admin_id'))
        batch_op.drop_column('created_by_admin_id')

    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_subscription_plans_created_by_admin_id'))
        batch_op.drop_column('created_by_admin_id')

    with op.batch_alter_table('op_lenders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_op_lenders_created_by_admin_id'))
        batch_op.drop_column('created_by_admin_id')

    with op.batch_alter_table('op_fixed_expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_op_fixed_expenses_created_by_admin_id'))
        batch_op.drop_column('created_by_admin_id')

    with op.batch_alter_table('op_expense_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_op_expense_categories_created_by_admin_id'))
        batch_op.drop_column('created_by_admin_id')

    with op.batch_alter_table('op_employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_op_employees_created_by_admin_id'))
        batch_op.drop_column('created_by_admin_id')

    with op.batch_alter_table('admin_role_permissions', schema=None) as batch_op:
        batch_op.drop_column('scope')

    # ### end Alembic commands ###
