"""Add attachment fields to op_monthly_expenses

Revision ID: bfb15b0f1fa4
Revises: a0e0fcc48c4b
Create Date: 2026-05-06 10:56:34.033862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfb15b0f1fa4'
down_revision = 'a0e0fcc48c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('op_monthly_expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('attachment_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('op_monthly_expenses', schema=None) as batch_op:
        batch_op.drop_column('attachment_filename')
        batch_op.drop_column('attachment_path')

    # ### end Alembic commands ###
